version: "3.9"
services:
  azure-cognitive-service-receipt:
    container_name: azure-cognitive-service-receipt
    image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/receipt:2.1
    environment:
      - EULA=accept
      - billing=https://forminterceptor.cognitiveservices.azure.com/
      - apikey=
      - AzureCognitiveServiceReadHost=http://azure-cognitive-service-read:5000
    ports:
      - "5000:5050"
    networks:
      - ocrvnet
  azure-cognitive-service-read:
    container_name: azure-cognitive-service-read
    image: mcr.microsoft.com/azure-cognitive-services/vision/read:3.2
    environment:
      - EULA=accept
      - billing=https://cogcomputer.cognitiveservices.azure.com/
      - apikey=
    networks:
      - ocrvnet

networks:
  ocrvnet:
    driver: bridge